import { useEffect, useState } from "react";
import { Sparkles, ThumbsUp, ThumbsDown, RefreshCw, AlertCircle } from "lucide-react";
import { getInsights, type InsightsResult } from "@/lib/api/insights.functions";
import { useI18n } from "@/lib/i18n";
import type { Statement } from "@/data/statements";
import { cn } from "@/lib/utils";

interface Props {
  statement: Statement;
  commentTexts: string[];
}

const labels = {
  nl: {
    title: "AI Inzichten",
    sub: "Automatische analyse van de discussie",
    summary: "Samenvatting",
    pros: "Belangrijkste argumenten vóór",
    cons: "Belangrijkste argumenten tegen",
    sentiment: "Algemene sentimentscore",
    positive: "Positief",
    neutral: "Neutraal",
    negative: "Negatief",
    loading: "AI analyseert de discussie…",
    retry: "Opnieuw proberen",
    error: "Inzichten konden niet worden geladen.",
    disclaimer: "Gegenereerd door AI op basis van stemverdeling en reacties. Kan fouten bevatten.",
    refresh: "Vernieuwen",
  },
  en: {
    title: "AI Insights",
    sub: "Automatic analysis of the discussion",
    summary: "Summary",
    pros: "Key arguments in favour",
    cons: "Key arguments against",
    sentiment: "Overall sentiment score",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    loading: "AI is analysing the discussion…",
    retry: "Try again",
    error: "Could not load insights.",
    disclaimer: "Generated by AI from vote distribution and comments. May contain errors.",
    refresh: "Refresh",
  },
};

export function AIInsights({ statement, commentTexts }: Props) {
  const { lang } = useI18n();
  const l = labels[lang];
  const [data, setData] = useState<InsightsResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [nonce, setNonce] = useState(0);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    getInsights({
      data: {
        statementNl: statement.nl,
        statementEn: statement.en,
        votes: statement.votes,
        comments: commentTexts.slice(0, 200),
        lang,
      },
    })
      .then((r) => {
        if (!cancelled) setData(r);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : "error");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [statement.id, lang, nonce]); // eslint-disable-line react-hooks/exhaustive-deps

  const sentimentMeta = data
    ? data.sentiment === "positive"
      ? { label: l.positive, cls: "bg-success/15 text-success border-success/30", dot: "bg-success" }
      : data.sentiment === "negative"
        ? { label: l.negative, cls: "bg-destructive/10 text-destructive border-destructive/30", dot: "bg-destructive" }
        : { label: l.neutral, cls: "bg-muted text-muted-foreground border-border", dot: "bg-muted-foreground" }
    : null;

  // map -100..100 to 0..100 for the bar
  const scorePct = data ? Math.round(((data.sentimentScore + 100) / 200) * 100) : 50;

  return (
    <section className="relative overflow-hidden rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/[0.04] via-card to-gold/[0.06] p-5 md:p-6 shadow-card-soft">
      <div className="pointer-events-none absolute -top-16 -right-16 h-40 w-40 rounded-full bg-primary/10 blur-3xl" />
      <div className="pointer-events-none absolute -bottom-20 -left-10 h-40 w-40 rounded-full bg-gold/10 blur-3xl" />

      <header className="relative flex items-start justify-between gap-3 mb-4">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-primary-glow text-primary-foreground shadow-md">
            <Sparkles className="h-5 w-5" />
          </div>
          <div>
            <h3 className="font-display text-lg md:text-xl leading-tight">{l.title}</h3>
            <p className="text-xs text-muted-foreground">{l.sub}</p>
          </div>
        </div>
        {!loading && (
          <button
            onClick={() => setNonce((n) => n + 1)}
            className="inline-flex items-center gap-1 rounded-full border border-border bg-background px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground hover:text-primary hover:border-primary transition-colors"
            aria-label={l.refresh}
          >
            <RefreshCw className="h-3 w-3" /> {l.refresh}
          </button>
        )}
      </header>

      {loading && <InsightsSkeleton text={l.loading} />}

      {error && !loading && (
        <div className="relative rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive flex items-start gap-2">
          <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
          <div className="flex-1">
            <p className="font-semibold">{l.error}</p>
            <button
              onClick={() => setNonce((n) => n + 1)}
              className="mt-2 inline-flex items-center gap-1 rounded-full bg-destructive px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-destructive-foreground"
            >
              <RefreshCw className="h-3 w-3" /> {l.retry}
            </button>
          </div>
        </div>
      )}

      {data && !loading && !error && sentimentMeta && (
        <div className="relative space-y-5 animate-in fade-in duration-500">
          {/* Sentiment badge + score bar */}
          <div className="flex flex-col sm:flex-row sm:items-center gap-3">
            <span
              className={cn(
                "inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-wider self-start",
                sentimentMeta.cls,
              )}
            >
              <span className={cn("h-1.5 w-1.5 rounded-full", sentimentMeta.dot)} />
              {sentimentMeta.label}
            </span>
            <div className="flex-1 min-w-0">
              <div className="flex items-center justify-between text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                <span>{l.sentiment}</span>
                <span className="tabular-nums">
                  {data.sentimentScore > 0 ? "+" : ""}
                  {data.sentimentScore}
                </span>
              </div>
              <div className="relative h-2 rounded-full bg-muted overflow-hidden">
                <div className="absolute inset-y-0 left-1/2 w-px bg-border" />
                <div
                  className={cn(
                    "h-full rounded-full transition-all duration-700",
                    data.sentiment === "positive"
                      ? "bg-success"
                      : data.sentiment === "negative"
                        ? "bg-destructive"
                        : "bg-muted-foreground",
                  )}
                  style={{ width: `${scorePct}%` }}
                />
              </div>
            </div>
          </div>

          {/* Summary */}
          {data.summary && (
            <div>
              <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary mb-1.5">{l.summary}</h4>
              <p className="text-sm md:text-base leading-relaxed text-foreground/85">{data.summary}</p>
            </div>
          )}

          {/* Pros / Cons */}
          <div className="grid gap-3 md:grid-cols-2">
            <ArgList icon={<ThumbsUp className="h-3.5 w-3.5" />} title={l.pros} items={data.pros} tone="pro" />
            <ArgList icon={<ThumbsDown className="h-3.5 w-3.5" />} title={l.cons} items={data.cons} tone="con" />
          </div>

          <p className="text-[10px] italic text-muted-foreground pt-1 border-t border-border/60">
            {l.disclaimer}
          </p>
        </div>
      )}
    </section>
  );
}

function ArgList({
  icon,
  title,
  items,
  tone,
}: {
  icon: React.ReactNode;
  title: string;
  items: string[];
  tone: "pro" | "con";
}) {
  const toneCls =
    tone === "pro"
      ? "border-success/30 bg-success/5 text-success"
      : "border-gold/40 bg-gold/10 text-gold-foreground";
  return (
    <div className="rounded-xl border border-border bg-card/60 p-3.5">
      <div className={cn("inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider mb-2.5", toneCls)}>
        {icon}
        {title}
      </div>
      {items.length === 0 ? (
        <p className="text-xs italic text-muted-foreground">—</p>
      ) : (
        <ul className="space-y-1.5">
          {items.map((it, i) => (
            <li key={i} className="flex gap-2 text-sm leading-snug text-foreground/85">
              <span className={cn("mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full", tone === "pro" ? "bg-success" : "bg-gold")} />
              <span>{it}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function InsightsSkeleton({ text }: { text: string }) {
  return (
    <div className="relative space-y-4">
      <div className="flex items-center gap-2 text-xs text-muted-foreground">
        <span className="inline-block h-2 w-2 animate-pulse rounded-full bg-primary" />
        {text}
      </div>
      <div className="h-2 w-full rounded-full bg-muted animate-pulse" />
      <div className="space-y-2">
        <div className="h-3 w-5/6 rounded bg-muted animate-pulse" />
        <div className="h-3 w-4/6 rounded bg-muted animate-pulse" />
        <div className="h-3 w-3/6 rounded bg-muted animate-pulse" />
      </div>
      <div className="grid gap-3 md:grid-cols-2">
        <div className="h-24 rounded-xl bg-muted/60 animate-pulse" />
        <div className="h-24 rounded-xl bg-muted/60 animate-pulse" />
      </div>
    </div>
  );
}
