/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultatenRouteImport } from './routes/resultaten'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscussieIdRouteImport } from './routes/discussie.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatenRoute = ResultatenRouteImport.update({
  id: '/resultaten',
  path: '/resultaten',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussieIdRoute = DiscussieIdRouteImport.update({
  id: '/discussie/$id',
  path: '/discussie/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resultaten': typeof ResultatenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/discussie/$id': typeof DiscussieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resultaten': typeof ResultatenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/discussie/$id': typeof DiscussieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resultaten': typeof ResultatenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/discussie/$id': typeof DiscussieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resultaten' | '/sitemap.xml' | '/discussie/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resultaten' | '/sitemap.xml' | '/discussie/$id'
  id: '__root__' | '/' | '/resultaten' | '/sitemap.xml' | '/discussie/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultatenRoute: typeof ResultatenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DiscussieIdRoute: typeof DiscussieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultaten': {
      id: '/resultaten'
      path: '/resultaten'
      fullPath: '/resultaten'
      preLoaderRoute: typeof ResultatenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussie/$id': {
      id: '/discussie/$id'
      path: '/discussie/$id'
      fullPath: '/discussie/$id'
      preLoaderRoute: typeof DiscussieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultatenRoute: ResultatenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DiscussieIdRoute: DiscussieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
